# Generated by Django 3.2.9 on 2021-12-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TKG-D', 'TKG Design'), ('TKG-E', 'TKG Edition'), ('TKG-L', 'TKG Luxe'), ('TKG-P', 'TKG Premium'), ('TKG-F', 'TKG Finest'), ('ADD', 'Addidos'), ('NIC', 'Nic'), ('PIN', 'Pineapple'), ('TSF', 'The South Face'), ('BC', 'British Connection'), ('PF', 'Perry Fred'), ('ZA', 'Zana'), ('OC', 'Ocean Island')], default=None, max_length=50)),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
