# Generated by Django 3.2.9 on 2021-12-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_colour'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(choices=[('TKG-D', 'TKG Design'), ('TKG-E', 'TKG Edition'), ('TKG-L', 'TKG Luxe'), ('TKG-P', 'TKG Premium'), ('TKG-F', 'TKG Finest'), ('ADD', 'Addidos'), ('NIC', 'Nic'), ('PIN', 'Pineapple'), ('TSF', 'The South Face'), ('BC', 'British Connection'), ('PF', 'Perry Fred'), ('ZA', 'Zana'), ('OC', 'Ocean Island')], default=None, max_length=50),
        ),
    ]
