# Generated by Django 3.2.9 on 2021-12-03 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('genders', '0001_initial'),
        ('colours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('price', models.IntegerField()),
                ('size', models.CharField(choices=[('XS', 'extra-small'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'extra-large')], default=None, max_length=10)),
                ('stock', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colours.colour')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genders.gender')),
            ],
        ),
    ]
