# Generated by Django 3.2.9 on 2021-12-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('price', models.IntegerField()),
                ('size', models.CharField(choices=[('XS', 'extra-small'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'extra-large')], default=None, max_length=10)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
