# Generated by Django 3.2.9 on 2021-12-02 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genders', '0001_initial'),
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='genders.gender'),
            preserve_default=False,
        ),
    ]
