# Generated by Django 3.2.9 on 2021-12-02 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colours', '0001_initial'),
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='colours.colour'),
        ),
    ]
