# Generated by Django 3.2.9 on 2021-12-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(choices=[('TKG Design', 'TKG Design'), ('TKG Edition', 'TKG Edition'), ('TKG Luxe', 'TKG Luxe'), ('TKG Premium', 'TKG Premium'), ('TKG Finest', 'TKG Finest'), ('Addidos', 'Addidos'), ('Nic', 'Nic'), ('Pineapple', 'Pineapple'), ('The South Face', 'The South Face'), ('British Connection', 'British Connection'), ('Perry Fred', 'Perry Fred'), ('Zana', 'Zana'), ('Ocean Island', 'Ocean Island')], default=None, max_length=50),
        ),
    ]
