# Generated by Django 3.2.9 on 2021-12-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Jeans', 'Jeans'), ('Dresses', 'Dresses'), ('Jumpers', 'Jumpers'), ('Shorts', 'Shorts'), ('Shirts', 'Shirts'), ('Trousers', 'Trousers'), ('Socks', 'Socks')], max_length=50)),
            ],
        ),
    ]
