# Generated by Django 3.2.9 on 2021-12-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='colour',
            field=models.CharField(blank=True, choices=[('Blk', 'Black'), ('Ylw', 'Yellow')], max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
