# Generated by Django 3.2.9 on 2021-12-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20211202_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='colour',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Yellow', 'Yellow'), ('Blue', 'Blue')], max_length=10),
        ),
    ]
