# Generated by Django 3.2.9 on 2021-12-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='colour',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Orange', 'Orange'), ('White', 'White')], max_length=10),
        ),
    ]
