# Generated by Django 3.2.9 on 2021-12-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
    ]
