# Generated by Django 3.2.9 on 2021-12-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Jeans', 'Jeans'), ('Dresses', 'Dresses'), ('Jumpers', 'Jumpers'), ('Shorts', 'Shorts'), ('Shirts', 'Shirts'), ('Trousers', 'Trousers'), ('Socks', 'Socks')], default=None, max_length=50),
        ),
    ]
